AWSTemplateFormatVersion: "2010-09-09"

Resources:
  EmailLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: email
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/LambdaRuntimeRole
      Runtime: python3.9
      Handler: index.handler
      Code:
        ZipFile: | 
          def handler(event, context):
            return { 
                "statusCode": 200, 
                "body": "Hello from Lambda!"
            } 
      Timeout: 30
      MemorySize: 128
