version: 0.2

phases:
  build:
    commands:
      - echo "Criando arquivo EmailSender.yml manualmente..."
      - cat <<EOT > EmailSender.yml
AWSTemplateFormatVersion: "2010-09-09"
Resources:
  SimpleEmailServiceIdentity:
    Type: AWS::SES::EmailIdentity
    Properties:
      EmailIdentity: "natalia.araujo1434@gmail.com"
EOT
      - echo "Arquivo criado! Exibindo conteúdo:"
      - aws cloudformation deploy \
          --template-file EmailSender.yml \
          --stack-name EmailSenderStack \
          --capabilities CAPABILITY_NAMED_IAM
