version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x  # Se necessário para dependências Python, ajuste conforme sua stack
    commands:
      - echo "Instalando dependências necessárias"
      - pip install --upgrade awscli  # Caso precise do AWS CLI

  build:
    commands:
      - echo "Fazendo o deploy do CloudFormation"
      - aws cloudformation deploy \
          --template-file CloudFormationTemplates/EmailSender.yml \
          --stack-name EmailSenderStack \
          --capabilities CAPABILITY_NAMED_IAM  # Caso você precise de permissões IAM no seu template

artifacts:
  files:
    - '**/*'  # Ou você pode especificar quais arquivos serão usados ou gerados durante o processo

cache:
  paths:
    - '/root/.m2/**/*'  # Se precisar de cache de dependências Maven ou outros, adicione os paths aqui
