AWSTemplateFormatVersion: "2010-09-09"

Resources:

  # Definir a identidade de e-mail (para envio de e-mails via SES)
  SimpleEmailServiceIdentity:
    Type: AWS::SES::EmailIdentity
    Properties:
      EmailIdentity: "natalia.araujo1434@gmail.com"

  # Função Lambda chamada "api_handler"
  apihandler:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: api_handler
      Runtime: python3.9
      Handler: lambda_function.lambda_handler
      Code:
        S3Bucket: sourcecoderepos001
        S3Key: lambda_function.zip
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 30
      MemorySize: 128

  # Função Lambda chamada "email"
  email:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: email
      Runtime: python3.9
      Handler: email_function.lambda_handler
      Code:
        S3Bucket: sourcecoderepos001
        S3Key: email_reminder.zip
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 30
      MemorySize: 128

  # Role do Lambda com permissões para execução
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: 
              - sts:AssumeRole
      Policies:
        - PolicyName: LambdaExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - ses:*
                  - sns:*
                  - states:*
                Resource: "*"

  # Step Function chamada MyStateMachine
  MyStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: MyStateMachine
      DefinitionS3Location:
        Bucket: sourcecoderepos001
        Key: step-function-template.json
      RoleArn: !GetAtt RoleForStepFunction.Arn

  # RoleForStepFunction com policy root e permissão para invocar funções Lambda
  RoleForStepFunction:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - states.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: RoleForStepFunctionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - ses:*
                  - states:*
                  - sns:*
                  - lambda:InvokeFunction  # Permissão para invocar funções Lambda
                Resource: "*"
