version: 0.2

phases:
  build:
    commands:
      - echo "Listando arquivos no diretório atual"
      - ls -R  # Lista todos os arquivos e subdiretórios
      - cat CloudFormationTemplates/EmailSender.yml  # Mostra o conteúdo do arquivo no log

