version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Instalando AWS CLI..."
      - pip install --upgrade awscli

  build:
    commands:
      - echo "Fazendo deploy da stack CloudFormation..."
      - aws cloudformation deploy \
          --template-file CloudFormationTemplates/EmailSender.yml \
          --stack-name EmailSenderStack \
          --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM
