version: 0.2

phases:
  build:
    commands:
      - echo "Criando arquivo EmailSender.yml manualmente..."
      - echo "AWSTemplateFormatVersion: '2010-09-09'" > EmailSender.yml
      - echo "Resources:" >> EmailSender.yml
      - echo "  SimpleEmailServiceIdentity:" >> EmailSender.yml
      - echo "    Type: 'AWS::SES::EmailIdentity'" >> EmailSender.yml
      - echo "    Properties:" >> EmailSender.yml
      - echo "      EmailIdentity: 'natalia.araujo1434@gmail.com'" >> EmailSender.yml
      - echo "Arquivo criado!"
      - cat EmailSender.yml  # Exibe o conteúdo do arquivo gerado
      - aws cloudformation deploy \
          --template-file EmailSender.yml \
          --stack-name EmailSenderStack \
          --capabilities CAPABILITY_IAM
