AWSTemplateFormatVersion: "2010-09-09"

Resources:
  # Identidade de E-mail para SES
  SimpleEmailServiceIdentity:
    Type: AWS::SES::EmailIdentity
    Properties:
      EmailIdentity: "natalia.araujo1434@gmail.com"

  # Função Lambda "email"
  EmailLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: email
      Runtime: python3.9
      Handler: index.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 30
      MemorySize: 128
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              return {"statusCode": 200, "body": "Hello from Email Lambda!"}

  # Função Lambda "api_handler"
  ApiHandlerLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: api_handler
      Runtime: python3.9
      Handler: index.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 30
      MemorySize: 128
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              return {"statusCode": 200, "body": "Hello from API Handler!"}

  # Role para as funções Lambda
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: 
              - sts:AssumeRole
      Policies:
        - PolicyName: LambdaExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - ses:*
                  - sns:*
                  - states:*
                Resource: "*"

  # Step Function
  MyStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: MyStateMachine
      RoleArn: !GetAtt RoleForStepFunction.Arn
      DefinitionString: |
        {
          "StartAt": "HelloWorld",
          "States": {
            "HelloWorld": {
              "Type": "Pass",
              "Result": "Hello from Step Function!",
              "End": true
            }
          }
        }

  # Role para Step Functions
  RoleForStepFunction:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: RoleForStepFunctionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - ses:*
                  - states:*
                  - sns:*
                  - lambda:InvokeFunction
                Resource: "*"
