version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo "Instalando AWS CLI..."
      - pip install awscli  # Caso ainda não esteja disponível no ambiente de build
  build:
    commands:
      - echo "Executando arquivos CloudFormation..."
      - for template in CloudFormationTemplates/*.yml; do
          echo "Deploying stack from $template...";
          stack_name=$(basename "$template" .yml);
          aws cloudformation deploy \
            --template-file $template \
            --stack-name $stack_name-stack \
            --capabilities CAPABILITY_NAMED_IAM || true;
        done

artifacts:
  files:
    - '**/*'
