version: 0.2

phases:
  install:
    commands:
      - echo "Instalando AWS CLI e outras dependências"
      - pip install awscli  # Instalar AWS CLI caso não tenha

  build:
    commands:
      - echo "Verificando se o arquivo de template do CloudFormation está presente"
      - ls -l CloudFormationTemplates/EmailSender.yml  # Verifica se o template existe

artifacts:
  files:
    - '**/*'  # Isso inclui todos os arquivos no repositório, se necessário
