phases:
  install:
    commands:
      - echo "Instalando AWS CLI..."
      - pip install awscli  # Caso a AWS CLI não esteja instalada

  build:
    commands:
      - echo "Executando o CloudFormation para EmailSender.yml..."
      - aws cloudformation create-stack --stack-name email-sender-stack --template-body file://EmailSender.yml --capabilities CAPABILITY_NAMED_IAM || echo "Stack já existe, tentando atualizar..."
      - aws cloudformation update-stack --stack-name email-sender-stack --template-body file://EmailSender.yml --capabilities CAPABILITY_NAMED_IAM


artifacts:
  files:
    - '**/*'
