version: 0.2

phases:
  build:
    commands:
      - wget -O EmailSender.yml https://raw.githubusercontent.com/Natalia-Araujo34/aws-email-sender/main/CloudFormationTemplates/EmailSender.yml
      - cat EmailSender.yml
      - aws cloudformation deploy \
          --template-file EmailSender.yml \
          --stack-name EmailSenderStack \
          --capabilities CAPABILITY_NAMED_IAM
