version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Instalando AWS CLI..."
      - pip install --upgrade awscli

  build:
    commands:
      - echo "Listando arquivos no diretório atual..."
      - ls -R  # Isso ajuda a depurar se os arquivos estão no local correto
      - echo "Fazendo deploy da stack CloudFormation..."
      - aws cloudformation deploy \
          --template-file creates3.yml \
          --stack-name EmailSenderStack \
          --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM

artifacts:
  files:
    - '**/*'  # Inclui todos os arquivos e subdiretórios no pacote de artefatos
